copyright = "Â© Einsteiners LLC 2025"
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "term"]
enableRobotsTXT = true
languageCode = "en"
timeZone = "Europe/Berlin"
timeout = "120s"
title = "Einsteiners Party Planner"

[params]
  defaultTheme = "light"
  description = "Example site for hugo-theme-gallery"
  title = "My Gallery"
  [params.author]
    email = "user@example.com"
    name = "Your Name"
  [params.socialIcons]
    facebook = "https://www.facebook.com/Einsteiners.events/"
    instagram = "https://www.instagram.com/einsteiners_events/"
    youtube = "https://www.youtube.com/@Einsteiners"
    email = "einsteinersllc@gmail.com"

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[imaging]
  quality = 75
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription"


[menu]
  [[menu.footer]]
    # name = "insteiners LLC"
    # url = "https://www.com/Einsteiners.events"
    # weight = 2

[services]
  [services.rss]
    limit = 100

[module]
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"